name: "Bug report"
description: Report an issue regarding Mythic.
title: "[bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a bug report. Please search existing issues before submitting, as the issue may have already been addressed.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, describe how in the description.
      placeholder: Description of happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: A step-by-step description of how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: input
    id: system-information
    attributes:
      label: Mac & App Information
      description: Help us understand the environment of the bug by providing information about your system and the app.
      placeholder: |
        - Model: MacBook Air M2 16gb
         - OS: macOS Sonoma 14.5
         - App Version: 0.3.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "If applicable, provide logs that may help us understand the issue."
      render: bash

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you confirm you did the following things.
      options:
        - label: I've made research efforts
          required: true
        - label: I've searched for existing issues
          required: true
