name: Build

on:
 push:
  paths:
   - '.github/workflows/build.yml'
   - 'Mythic.xcodeproj/**'
   - 'Mythic/**'
 pull_request:
  paths:
   - '.github/workflows/build.yml'
   - 'Mythic.xcodeproj/**'
   - 'Mythic/**'
 workflow_dispatch:

jobs:
 build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install Command Line Tools for Xcode (if it's not installed)
      run: |
         if xcode-select --version >/dev/null 2>&1; then
             echo "Xcode Command Line Tools is installed, skipping."
         else
             echo "Xcode Command Line Tools is not installed, installing."
             xcode-select --install
         fi

    - name: Build
      run: xcodebuild -scheme Mythic CODE_SIGNING_ALLOWED=NO SWIFTLINT=NO
